---
# tasks file for k3s

- name: "Gather facts"
  ansible.builtin.gather_facts:

- name: Install nano package
  ansible.builtin.apt:
    name: nano
    state: present
  when: ansible_os_family == "Debian"

- name: Install nano package
  ansible.builtin.apk:
    name: nano
    state: present
  when: ansible_os_family == "Alpine"

- name: Include preparation role
  ansible.builtin.include_role:
    name: prereq
  when: inventory_hostname in groups.k3s_cluster

- name: Include download role
  ansible.builtin.include_role:
    name: download
  when: inventory_hostname in groups.k3s_cluster

# - hosts: k3s_master
#   roles:
#     - role: k3s/master
#       become: true

# - hosts: k3s_node
#   roles:
#     - role: k3s/node
#       become: true

# - hosts: k3s_master
#   roles:
#     - role: post
#       become: true
