---
# tasks file for k3s

- name: "Gather facts"
  ansible.builtin.gather_facts:

- name: Include preparation tasks
  ansible.builtin.include_tasks:
    file: pre/prerequisites.yml
  when: inventory_hostname in groups.k3s_cluster

- name: Include download tasks
  ansible.builtin.include_tasks:
    file: pre/download.yml
  when: inventory_hostname in groups.k3s_cluster

- name: Include k3s master tasks
  ansible.builtin.include_tasks:
    file: k3s/master/tasks/main.yml
  when: inventory_hostname in groups.k3s_master

# - hosts: k3s_node
#   roles:
#     - role: k3s/node
#       become: true

# - hosts: k3s_master
#   roles:
#     - role: post
#       become: true
