---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  # - name: alpine_3.18
  #   image: docker.io/alpine:3.18
  #   pre_build_image: true
  #   groups:
  #     - k3s_master
  #   children:
  #     - k3s_cluster
  # - name: alpine_3.17
  #   image: docker.io/alpine:3.17
  #   pre_build_image: true
  #   groups:
  #     - k3s_node
  #   children:
  #     - k3s_cluster
  # - name: alpine_3.16
  #   image: docker.io/alpine:3.16
  #   pre_build_image: true
  #   groups:
  #     - k3s_node
  #   children:
  #     - k3s_cluster
  # - name: debian_bookworm
  #   image: docker.io/debian:bookworm
  #   pre_build_image: true
  #   groups:
  #     - k3s_master
  #   children:
  #     - k3s_cluster
  #   privileged: True
  #   capabilities:
  #     - SYS_ADMIN
  #   sysctls:
  #     net.ipv4.ip_forward: 1
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  # - name: debian_bullseye
  #   image: docker.io/debian:bullseye
  #   pre_build_image: true
  #   groups:
  #     - k3s_node
  #   children:
  #     - k3s_cluster
  #   privileged: True
  #   capabilities:
  #     - SYS_ADMIN
  #   sysctls:
  #     net.ipv4.ip_forward: 1
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  - name: ubuntu_23.04
    image: docker.io/ubuntu:23.04
    pre_build_image: true
    groups:
      - k3s_master
    children:
      - k3s_cluster
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    tmpfs:
      - /tmp
      - /run
  - name: ubuntu_22.04
    image: docker.io/ubuntu:22.04
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    tmpfs:
      - /tmp
      - /run
  - name: ubuntu_20.04
    image: docker.io/ubuntu:20.04
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    tmpfs:
      - /tmp
      - /run
  # - name: ubuntu_18.04
  #   image: docker.io/ubuntu:18.04
  #   pre_build_image: true
  #   groups:
  #     - k3s_node
  #   children:
  #     - k3s_cluster
  #   privileged: True
  #   capabilities:
  #     - SYS_ADMIN
  #   sysctls:
  #     net.ipv4.ip_forward: 1
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  # - name: ubuntu_16.04
  #   image: docker.io/ubuntu:16.04
  #   pre_build_image: true
  #   groups:
  #     - k3s_node
  #   children:
  #     - k3s_cluster
  #   privileged: True
  #   capabilities:
  #     - SYS_ADMIN
  #   sysctls:
  #     net.ipv4.ip_forward: 1
  #   volumes:
  #     - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
# provisioner:
#   name: ansible
#   log: true
#   env:
#     ANSIBLE_ROLES_PATH: "../../roles"
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
