---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: master-1
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    image: ubuntu:20.04
    pre_build_image: true
  - name:  master-2
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    image: ubuntu:20.04
    pre_build_image: true
  - name:  master-3
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    image: ubuntu:20.04
    pre_build_image: true
