---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: alpine_3.18
    image: docker.io/alpine:3.18
    pre_build_image: true
    groups:
      - k3s_master
    children:
      - k3s_cluster
  - name: alpine_3.17
    image: docker.io/alpine:3.17
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
  - name: alpine_3.16
    image: docker.io/alpine:3.16
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
  - name: debian_bookworm
    image: docker.io/debian:bookworm
    pre_build_image: true
    groups:
      - k3s_master
    children:
      - k3s_cluster
  - name: debian_bullseye
    image: docker.io/debian:bullseye
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
  - name: ubuntu_22.04
    image: docker.io/ubuntu:22.04
    groups:
      - k3s_master
    children:
      - k3s_cluster
    pre_build_image: true
  - name: ubuntu_20.04
    image: docker.io/ubuntu:20.04
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
  - name: ubuntu_18.04
    image: docker.io/ubuntu:18.04
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
  - name: ubuntu_16.04
    image: docker.io/ubuntu:16.04
    pre_build_image: true
    groups:
      - k3s_node
    children:
      - k3s_cluster
# provisioner:
#   name: ansible
#   log: true
#   env:
#     ANSIBLE_ROLES_PATH: "../../roles"
