---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: debian_bookworm
    image: docker.io/debian:bookworm
    pre_build_image: true
  - name: debian_bullseye
    image: docker.io/debian:bullseye
    pre_build_image: true
  - name: ubuntu_22.04
    image: docker.io/ubuntu:22.04
    pre_build_image: true
  - name: ubuntu_20.04
    image: docker.io/ubuntu:20.04
    pre_build_image: true
  - name: ubuntu_18.04
    image: docker.io/ubuntu:18.04
    pre_build_image: true
  - name: ubuntu_16.04
    image: docker.io/ubuntu:16.04
    pre_build_image: true
